-------------------------------------------------------------------------
-- Design unit: R8 simutation test bench
-- Description: R8 processor connected to a RAM memory
--      The RAM memory is able to load image files generated by the R8 simulator             
-------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;        
use work.R8_pkg.all;

entity R8_tb is
end R8_tb;

architecture behavioral of R8_tb is
    
      signal clk : std_logic := '0';  
      signal rst: std_logic;
    signal port_ioA : std_logic_vector (15 downto 0);
    signal port_ioB : std_logic_vector (15 downto 0)
    
begin
    
    PROCESSOR: entity work.R8_uC
        port map (
            clk         => clk, 
            rst         => rst,
			port_ioA     => port_ioA,
            port_ioB    => port_ioB
        );
        
    -- Generates the clock signal            
    clk <= not clk after 10 ns;
    
    -- Generates the reset signal
    rst <='1', '0' after 5 ns;        

end behavioral;